{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "prometheus-example-app.fullname" . }}
  labels:
    {{- include "prometheus-example-app.labels" . | nindent 4 }}
    {{- with .Values.serviceMonitor.labels }}
    {{- include "prometheus-example-app.renderStringMap" . | trimSuffix "\n" | nindent 4 }}
    {{- end }}
  {{- with .Values.serviceMonitor.annotations }}
  annotations:
    {{- include "prometheus-example-app.renderStringMap" . | trimSuffix "\n" | nindent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "prometheus-example-app.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http
      path: {{ .Values.serviceMonitor.path }}
      interval: {{ .Values.serviceMonitor.interval }}
      scrapeTimeout: {{ .Values.serviceMonitor.scrapeTimeout }}
{{- end }}
